version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  # Terraform Projects
  - package-ecosystem: terraform
    directory: /cloudflare
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /github
    schedule:
      interval: weekly
